### ISSUE TITLE
Crash, Freeze

### ISSUE THREAD

**Issue by erdnuesse** [theothernt/AerialViews#143] opened 2024-05-24 14:43 UTC
**What were you trying to do...**
Regular usage

**And what actually happened (ie. describe the bug)...**
Crashing / Freezing
Picture no longer moves, Time stays frozen at time of crash. 
Device not responsive to network or Remote, needs cold restart.

**What kind of device do you have? (eg. Nvidia Shield, Sony TV, etc)...**
Chromecast with Google TV, TVOS 12, Patchlevel March 2024

Idk if it's networking issues, RAM usage, app crashing or what. Can't debug or change settings to lower the load for testing. Also, freezes with kodi in background, not sure if crashes occur while other apps running as it's hard to test during regular usage.

**Comment by theothernt** [comment] 2024-05-25 14:05
This issue sounds very strange - and I use a Chromecast with Google TV 4K as well.

My initial guess is that it's a conflict with another app. Kodi has caused issues with Aerial Views for a few users before, but I think they were using a Nvidia Shield.

Can you let me know if the issue happens with any other app or just Kodi?

**Comment by theothernt** [comment] 2024-05-31 12:26
> I haven't seen it with another app yet. I left it running over night in other apps, but AFAIR it was just Kodi. However, I can't say it happens every time I leave Kodi running. But, Aerial Views needed to run for a while before it froze.

So, there are a number of things we can try to narrow down what the issue is...

**Storage** - Although I don't think storage is the issue, would it be possible to turn off local storage in Aerial Views and try a remote source only, like the Apple videos?

**Dev Options** - It depends on what options you've changed from the default, have you enabled "Disable HW overlays" by chance?

**Comment by erdnuesse** [comment] 2024-05-31 12:33
> So, there are a number of things we can try to narrow down what the issue is...
> 
> **Storage** - Although I don't think storage is the issue, would it be possible to turn off local storage in Aerial Views and try a remote source only, like the Apple videos?
Thing is, I do not have local sources. My guess was that the remote sources in use need too much cache which would lead to arbitrary crashes as they would differ in filesize each time hence the unpredictability of said freezes.
(will check any setting as well, but AFAIR there wasn't even a setting to select local sources)

> 
> **Dev Options** - It depends on what options you've changed from the default, have you enabled "Disable HW overlays" by chance?
I would say no, as I used dev opts just for the "force apps to ext. storage" possibility, but I'll double-check just to make sure.

**Comment by theothernt** [comment] 2024-06-07 21:34
I'll close this issue for the moment, let me know if you manage to narrow down the issue.

**Closed by theothernt** 2024-06-07 21:34 UTC
Labels: bug
