### ISSUE TITLE
Capabilities. Max video resolution on Sony Bravia A80j

### ISSUE THREAD

**Issue by tsoodla** [theothernt/AerialViews#40] opened 2022-01-15 18:05 UTC
First of all - the video playback is smooth and beautiful with settings to 4k/hdr. However, the max video resolution on the capabilities screen is showing only 1920x1080 @ 60,00 Hz.

Is it running at 4k at all?

![IMG_7416](https://user-images.githubusercontent.com/12015698/149632769-c539e1fd-142d-4542-9e9b-91c83a2f7f81.jpg)

**Comment by theothernt** [comment] 2022-01-15 18:38
Hmmm... from looking at this, I'm not sure. It is possible the app is wrong due to Android being a bit different of some TVs/device. If you could check a couple of things for me...

1. When you use apps, does the TV report the resolution and frame rate (some TVs do, some don't)
2. Can you try a 1080p HDR and 4K HDR video and see if there is a difference in sharpness - there should be! You can also turn off random video order in Settings > Interface > Shuffle videos to see the same video on startup.

**Comment by Plazzmex** [comment] 2022-01-15 21:38
Same for me on Philips 4k TV, it shows max resolution 1080 at 60hz. I use 4k sdr because HDR doesn't work on Philips tv as you know

**Comment by tsoodla** [comment] 2022-01-16 11:50
> 1. When you use apps, does the TV report the resolution and frame rate (some TVs do, some don't)
There is no way to see the resolution and frame rate on Sony while using apps.

> 2. Can you try a 1080p HDR and 4K HDR video and see if there is a difference in sharpness - there should be! 
I can not see the difference. The picture is sharp in both cases.

**Comment by theothernt** [comment] 2022-01-16 13:19
I did some more research, it appears that some Sony 4K TVs (depending on the generation, model, etc) only play video in apps at 1080p.

One other thing to try... open the YouTube app, play a video, bring up the options for the video (button with 3 dots) and enable "Stats for Nerds". It will overlay a black box on the video with a ton of info. Look for "Viewport / Frames", if that doesn't report 4K resolution then I think we're out of luck.

I'm still trying to find a reason and understand this issue myself as, correct me of I'm wrong, the Sony A80J is a 2021 model TV and it's not a low-end or budget model?

@Plazzmex Philips TVs might be in the same boat but I honestly don't understand why?! ...both the Google TV and Nvidia Shield do run videos at 4K based on info provided by others.

**Comment by tsoodla** [comment] 2022-01-16 14:07
> One other thing to try... open the YouTube app, play a video, bring up the options for the video (button with 3 dots) and enable "Stats for Nerds". It will overlay a black box on the video with a ton of info. Look for "Viewport / Frames", if that doesn't report 4K resolution then I think we're out of luck.

Youtube reports 1920x1080*2.00. Times two!? I am wondering, is that the same as 4k? [Here](https://twitter.com/teamyoutube/status/930277424323088384?lang=en) is TeamYouTube trying to explain it but it still remains confusing to me.

Netflix seems to report 2160 on 4k movie.
![IMG_7418](https://user-images.githubusercontent.com/12015698/149663407-9fd83cf2-2a48-4431-9b6c-9c8799ad7b8a.jpg)
![IMG_7419](https://user-images.githubusercontent.com/12015698/149663410-3d890c26-8d97-48b0-882e-ee61aa5c5712.jpg)
![IMG_7420](https://user-images.githubusercontent.com/12015698/149663412-f5842d71-c219-4cde-b35e-e517aaf14879.jpg)

**Comment by theothernt** [comment] 2022-01-16 14:52
Thanks for all the additional info. YouTube seems to be reporting a 4K screen (2 x 1080p is a weird way of saying 4K ie. 2160p) but the other apps aren't - just the video resolution. For example, I have an old 1080p TV but in YouTube I can set the video 'quality' to 4K.

I think one of the only ways to test this is to have an external Android TV device like a Google TV or Nvidia Shield which do output at 4K then compare video quality with the TV - but I understand that's not really possible.

I am looking into other ideas, it is possible for the video player in Aerial Views to detect when video is down-sampled (ie. resized) eg. it's playing a 4K video but scaling it down to 1080p for the TV. I'll have to add some code but it should be possible to show a notification on the video when that happens.

Sorry about all this confusion - I wish I had a clear answer or fix 😐

**Comment by tsoodla** [comment] 2022-01-16 14:57
Thank you for your work  on this.

**Comment by theothernt** [comment] 2022-01-16 15:08
No probs - I'll report back in a few days when I have an update!

**Comment by shareefalis** [comment] 2022-01-17 03:22
I think it may be just UI rendering pipeline reporting it is in 1080p. Hardware accelerated decoding bypasses the UI pipeline, the feature [tunneledl](https://medium.com/google-exoplayer/tunneled-video-playback-in-exoplayer-84f084a8094d) does not go back to Application Processor (AP) and GPU . it stays within scope of hardware decoding pipeline and  write to frame buffer directly in display hardware, which enable Dolby vision and 4k HDR bypassing  AP/GPU completely.. In order to save processing resources, they decided to render the UI as 1080p..

**Comment by theothernt** [comment] 2022-01-17 12:48
So I think I've found the solution. Android has a couple of methods to get the physical screen (viewport) size, an old way and a new way - the recommended ways according to the official docs.

But as Android is **not** identical on all devices, Sony decided that their 4K TVs should report their physical size as 1080p !? (different from the UI resolution, which is already reported correctly in the app). Sony then expect you to check for a "4k feature" of the TV (`com.sony.dtv.hardware.panel.qfhd`) and then you can assume it's a 4K screen ?!

I did wonder why ExoPlayer (a player component made by Google) had its own helper method to get the physical screen size... and now I know 🤨

This fix will be in the next beta release, and later in a Store update.

**Closed** 2022-01-17 18:53 UTC
Labels: bug, question

**Comment by theothernt** [comment] 2022-02-12 15:05
If the issue is fixed in v1.1 beta 1 or 2 - do let me know.

If you don't want to sideload the APK, v1.1 will be in the Play Store in the next week to 10 days (around 22nd of Feb)

**Comment by tsoodla** [comment] 2022-02-12 17:22
Thanks, I will report back. I will wait for Play Store release.

**Comment by tsoodla** [comment] 2022-03-02 10:20
Looks good
![IMG_7502](https://user-images.githubusercontent.com/12015698/156342969-3ba74ea3-b6f3-49c5-a6ff-a78544818503.jpeg)
d

**Comment by theothernt** [comment] 2022-03-02 13:28
@tsoodla fantastic, thanks for the pic!
