### ISSUE TITLE
Home button does not exit screensaver 

### ISSUE THREAD

**Issue by Christofo** [theothernt/AerialViews#152] opened 2024-06-19 03:47 UTC
Hi,

I have a ONN 4K Pro. I just setup Aerial Views to be the default screensaver using ADB. 

When the screensaver launches after my set time, hitting the home button on the remote does nothing. I would expect it to exit out of the screensaver. Is this expected behavior? 

Thanks!

**Comment by theothernt** [comment] 2024-06-19 12:32
No, it's not the expected behaviour.

Depending on what settings you have, it's possible for the screensaver to use the d-pad up/down/left/right and ok button - but it's not possible for the app to use or block the home button.

When you use the 'test' option in Aerial Views, does it home button work in that case?

**Comment by Christofo** [comment] 2024-06-19 12:52
> No, it's not the expected behaviour.
> 
> Depending on what settings you have, it's possible for the screensaver to use the d-pad up/down/left/right and ok button - but it's not possible for the app to use or block the home button.
> 
> When you use the 'test' option in Aerial Views, does it home button work in that case?

Yes, when using the test option the home button works. I also tried with and without "Allow media button pass-through" but that doesn't fix the issue.

**Comment by theothernt** [comment] 2024-06-19 14:08
By chance, are you using a custom launcher or button remapper?

**Comment by Christofo** [comment] 2024-06-19 14:16
> By chance, are you using a custom launcher or button remapper?

Ah, yes. I'm using Projectivy. I fixed the issue:

Disabled stock launcher through ADB
In Projectivy settings, uncheck "Override current launcher"

Now the home button exits the screensaver as expected.

Thank you!

**Comment by mikesprandel** [comment] 2024-06-24 17:39
I wanted to chime in and say that this did not help with my device. Same model, same issue.

Aerial Views is only exiting with Back. 
After disabling stock launcher via ADB and disabling the Provectivy Override, I am returned to a black screen with no launcher at all. 
I resolved this issue by installing Launch Manager 1.0.4 for Android TV. I wonder if @Christofo had that configured as well, since the other steps listed in the fix do not seem to work.

**Comment by theothernt** [comment] 2024-06-24 20:21
> I wanted to chime in and say that this did not help with my device. Same model, same issue.
> 
> Aerial Views is only exiting with Back. After disabling stock launcher via ADB and disabling the Provectivy Override, I am returned to a black screen with no launcher at all. I resolved this issue by installing Launch Manager 1.0.4 for Android TV. I wonder if @Christofo had that configured as well, since the other steps listed in the fix do not seem to work.

Just to confirm, your issue with the home button is now fixed?

**Comment by mikesprandel** [comment] 2024-06-24 20:40
> > I wanted to chime in and say that this did not help with my device. Same model, same issue.
> > Aerial Views is only exiting with Back. After disabling stock launcher via ADB and disabling the Provectivy Override, I am returned to a black screen with no launcher at all. I resolved this issue by installing Launch Manager 1.0.4 for Android TV. I wonder if @Christofo had that configured as well, since the other steps listed in the fix do not seem to work.
> 
> Just to confirm, your issue with the home button is now fixed?

No - not without another utility involved (Launcher Manager).

**Comment by theothernt** [comment] 2024-06-28 22:05
Does anyone know if other screensavers also have this issue?

Also, I have reported the issue to the developer of Projectivy.

**Comment by Christofo** [comment] 2024-06-28 22:14
@mikesprandel I was not using launcher manager. All I did was disable the stock launcher using:

"adb shell pm disable-user --user 0 com.google.android.apps.tv.launcherx"
"adb shell pm disable-user --user 0 com.google.android.tungsten.setupwraith"

I did not have this issue using the stock screensaver, if that helps @theothernt

**Comment by theothernt** [comment] 2024-07-23 15:49
I'm going to close the issue until I get an update.

I still have no idea why the home button doesn't exist the screensaver under certain instances as it's not possible for my app to hook, use or block that button.

**Closed by theothernt** 2024-07-23 15:49 UTC
Labels: question
