### ISSUE TITLE
POI showing filenames

### ISSUE THREAD

**Issue by Thoroslives** [theothernt/AerialViews#108] opened 2023-06-05 22:05 UTC
Been using for a while on a Nvidia Shield pulling files locally from a samba share on my server. POI namrs havr been working fine so far but have recently noticed some of them, which seem to be any non apple ones ive found linked around this github are now showing file names as POI. (Such as video_inspire_oregon_lone_ranch_beach_00015)

Settings are 
- Show video location, title or points of interest - Points Of Interest
- Use filename as Location - On (toggling doesnt fix)

Running 1.4.3

**Comment by theothernt** [comment] 2023-06-05 22:28
Thanks for reporting the issue. What you're seeing is a bug, basically a copy and paste mistake by me, but it's fixed in 1.4.4 due out soon.

Did you only see this issue with one video?

**Comment by Thoroslives** [comment] 2023-06-05 22:31
> Thanks for reporting the issue. What you're seeing is a bug, basically a copy and paste mistake by me, but it's fixed in 1.4.4 due out soon.
> 
> Did you only see this issue with one video?

Nah it happens with essentially any video that isnt an official apple one. Ive got about 140 vids that the app pulls which includes the apple ones.

**Comment by theothernt** [comment] 2023-06-05 22:36
Hmmm... it's possible there's another issue then. 

Let me check on it tomorrow, I'll use a mix of a Apple + Community videos.

**Comment by Thoroslives** [comment] 2023-06-05 22:38
> Hmmm... it's possible there's another issue then.
> 
> Let me check on it tomorrow, I'll use a mix of a Apple + Community videos.

Im sorry, if you give me till this evening ill go through and can tell you which ones work and dont

**Comment by theothernt** [comment] 2023-06-05 22:45
> Im sorry, if you give me till this evening ill go through and can tell you which ones work and dont

That's ok, I know what the issue is - I realised right after I replied. 

Basically, POIs are not added to videos from SMB, USB storage as I forgot to implement it. 

I'll fix it tomorrow - and thank you so much for letting me know! 😅

**Comment by Thoroslives** [comment] 2023-06-05 22:47
> > Im sorry, if you give me till this evening ill go through and can tell you which ones work and dont
> 
> That's ok, I know what the issue is - I realised right after I replied.
> 
> Basically, POIs are not added to videos from SMB, USB storage as I forgot to implement it.
> 
> I'll fix it tomorrow - and thank you so much for letting me know! 😅

Awesome, more than happy to help, let me know when you push and ill give it a test

**Comment by theothernt** [comment] 2023-06-06 14:10
Ok, I've added a quick fix which should include POI info for community videos... [Aerial Views v1.4.4 beta2](https://www.dropbox.com/s/upso04mikqukmht/aerial-views-1.4.4-beta2.apk?dl=0)

Let me know how you get on!

**Comment by Thoroslives** [comment] 2023-06-07 19:15
> Ok, I've added a quick fix which should include POI info for community videos... [Aerial Views v1.4.4 beta2](https://www.dropbox.com/s/upso04mikqukmht/aerial-views-1.4.4-beta2.apk?dl=0)
> 
> Let me know how you get on!

Sorry ive sent sway with work so i wont be able to test it out till next week.

**Comment by theothernt** [comment] 2023-06-07 20:43
> Sorry ive sent sway with work so i wont be able to test it out till next week.

No problem at all, I'll let you know when I release it.

**Comment by Thoroslives** [comment] 2023-06-13 22:33
For some reason the 1.44 beta patch wont install over the existing installation, am I gonna have to do a cleaninstall?

**Comment by theothernt** [comment] 2023-06-13 22:37
> For some reason the 1.44 beta patch wont install over the existing installation, am I gonna have to do a cleaninstall?

How are you trying to install it?

**Closed** 2023-06-13 22:41 UTC
Labels: bug

**Comment by theothernt** [comment] 2023-06-13 22:51
Great! glad it's fixed - the fix will be included in the next release of the app.

**Comment by theothernt** [comment] 2023-10-03 12:32
Just to double check, are you running the latest version of the app (1.5.2 currently) ?

I ask as I'm getting crash reports from a user running 1.4.4-beta which is quite old.

**Comment by Thoroslives** [comment] 2023-10-03 20:10
> Just to double check, are you running the latest version of the app (1.5.2 currently) ?
> 
> I ask as I'm getting crash reports from a user running 1.4.4-beta which is quite old.

Im still running that beta apk you gave me, its been flawless

**Comment by theothernt** [comment] 2023-10-04 14:13
> > Just to double check, are you running the latest version of the app (1.5.2 currently) ?
> > I ask as I'm getting crash reports from a user running 1.4.4-beta which is quite old.
> 
> Im still running that beta apk you gave me, its been flawless

Glad to hear it!

I would recommend updating to a non-beta version when you have time. If you update to v1.5.2, it will carry your preferences forward - there are also new videos and features 😊
